version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the application...
      - yarn build
  post_build:
    commands:
      - echo Post-build commands...
      # Any additional commands you need can be added here

artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory where the compiled files are stored

cache:
  paths:
    - node_modules/**/*

env:
  variables:
    NODE_OPTIONS: "--openssl-legacy-provider"
    PORT: "8080"
