version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the application...
      - yarn run build
  post_build:
    commands:
      - echo Installing serve globally...
      - yarn global add serve
      - echo Copying Procfile to build directory...
      - cp Procfile build/
      - echo Copying Procfile finished...
     
   
      # Any additional commands you need can be added here

artifacts:
  files:
    - 'build/**/*'
  base-directory: build # The build directory where the compiled files are stored
