version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - ulimit -n 2048
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Post-build commands...
      - npm install -g serve
      # Any additional commands you need can be added here

artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory where the compiled files are stored


