version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build
  post_build:
    commands:
      - echo Copying Procfile to build directory...
      - cp Procfile build/
      - echo Installing serve globally...
   
      # Any additional commands you need can be added here

artifacts:
  files:
    - 'build/**/*'
    - 'build/Procfile'
  base-directory: build # The build directory where the compiled files are stored

cache:
  paths:
    - 'node_modules/**/*'
