version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - yarn install
      
  build:
    commands:
      - echo Building the application...
      - yarn build
      


artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory where the compiled files are stored
