version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Cleaning up previous installations...
      - rm -rf node_modules
      - npm install -g npm@9
      - yarn cache clean
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the application...
      - yarn build
      - yarn add @babel/plugin-proposal-private-property-in-object
  post_build:
    commands:
      - echo Copying additional files...
      - cp -r ./src ./build/src
      - cp -r public ./build/public
      - cp package.json ./build/
      - cp .babelrc ./build/
      - cp yarn.lock ./build/
      - cp babel.config.js ./build/
      - echo Additional files copied...

artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory where the compiled files are stored
