version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - yarn install
  build:
    commands:
      - echo Building the application...
      - yarn run build
  post_build:
    commands:
      - echo Installing serve globally...
      - npm install -g serve
      - echo Listing files in the root directory before copying...
      - ls -la
      - echo Listing files in the build directory before copying...
      - ls -la build
      - echo Copying Procfile to build directory...
      - cp Procfile build/
      - echo Listing files in the build directory after copying...
      - ls -la build
      - echo Copying Procfile finished...
   
artifacts:
  files:
    - '**/*'
  base-directory: build # The build directory where the compiled files are stored
